 


# Notice : After completing this configuration, it must be pushed into the config-server and removed from the project directory. Please contact Farouk or Salmen before deploying your application in the integration environement

 
management:
    security:
        enabled: false
security:
    basic:
        enabled: false

spring:
    redis:
        host: redis
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    datasource:
        url: jdbc:sqlserver://192.168.0.117:1415;database=gcliniqueegypte
        username: SA
        password: 123
        
    jpa:
        database-platform: org.hibernate.dialect.SQLServer2012Dialect
        database: SQL_SERVER
        show-sql: true
        hibernate:
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate.default_schema: param_achat
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
    

liquibase:
    contexts: prod
    enabled: false

 
server:
    contextPath: /template
    port: 80
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024
 
lang:
    secondary: ar
    
 

